var icons = [
	'<i class="wi wi-tornado"></i>',			//tornado
	'<i class="wi wi-rain-wind"></i>',			//tropical storm
	'<i class="wi wi-tornado"></i>',			//hurricane
	'<i class="wi wi-thunderstorm"></i>',		//severe thunderstorms
	'<i class="wi wi-thunderstorm"></i>',		//thunderstorms
	'<i class="wi wi-rain-mix"></i>',			//mixed rain and snow
	'<i class="wi wi-rain-mix"></i>',			//mixed rain and sleet
	'<i class="wi wi-rain-mix"></i>',			//mixed snow and sleet
	'<i class="wi wi-rain-mix"></i>',			//freezing drizzle
	'<i class="wi wi-cloudy"></i>',				//drizzle
	'<i class="wi wi-rain"></i>',				//freezing rain
	'<i class="wi wi-rain"></i>',				//showers
	'<i class="wi wi-rain"></i>',				//showers
	'<i class="wi wi-snow"></i>',				//snow flurries
	'<i class="wi wi-snow"></i>',				//light snow showers
	'<i class="wi wi-showers"></i>',			//blowing snow
	'<i class="wi wi-snow"></i>',				//snow
	'<i class="wi wi-hail"></i>',				//hail
	'<i class="wi wi-rain-mix"></i>',			//sleet
	'<i class="wi wi-dust"></i>',				//dust
	'<i class="wi wi-fog"></i>',				//foggy
	'<i class="wi wi-day-haze"></i>',			//haze
	'<i class="wi wi-smoke"></i>',				//smoky
	'<i class="wi wi-strong-wind"></i>',		//blustery
	'<i class="wi wi-strong-wind"></i>',		//windy
	'<i class="wi wi-snowflake-cold"></i>',		//cold
	'<i class="wi wi-cloudy"></i>',				//cloudy
	'<i class="wi wi-night-cloudy"></i>',		//mostly cloudy (night)
	'<i class="wi wi-day-cloudy"></i>',			//mostly cloudy (day)
	'<i class="wi wi-night-cloudy"></i>',		//partly cloudy (night)
	'<i class="wi wi-day-cloudy"></i>',			//partly cloudy (day)
	'<i class="wi wi-night-clear"></i>',		//clear (night)
	'<i class="wi wi-day-sunny"></i>',			//sunny
	'<i class="wi wi-night-clear"></i>',		//fair (night)
	'<i class="wi wi-day-sunny"></i>',			//fair (day)
	'<i class="wi wi-hail"></i>',				//mixed rain and hail
	'<i class="wi wi-hot"></i>',				//hot
	'<i class="wi wi-storm-showers"></i>',		//isolated thunderstorms
	'<i class="wi wi-storm-showers"></i>',		//scattered thunderstorms
	'<i class="wi wi-storm-showers"></i>',		//scattered thunderstorms
	'<i class="wi wi-showers"></i>',			//scattered showers
	'<i class="wi wi-sleet"></i>',				//heavy snow
	'<i class="wi wi-snow"></i>',				//scattered snow showers
	'<i class="wi wi-sleet"></i>',				//heavy snow
	'<i class="wi wi-cloudy"></i>',				//partly cloudy
	'<i class="wi wi-storm-showers"></i>',		//thundershowers
	'<i class="wi wi-snow"></i>',				//snow showers
	'<i class="wi wi-storm-showers"></i>'		//isolated thundershowers
];
